### ISSUE TITLE
Drop non-client-side dependencies

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/cilantro#70]
This translates to dropping the Python/Django dependency. This lays the foundation for using Cilantro as a client to multiple separate Harvest instances. This will solve one facet of the [100 Harvest Problem&trade;](cbmi/100-harvests).

In order for this to work a few requirements must be met:
- [x] Cilantro's JavaScript components must be a standalone encapsulated modules (when built and minified) https://github.com/cbmi/cilantro/issues/71
  - This ensures flexibility for integration in other custom-made clients
- [x] A _very simple_ base HTML page with CSS must be supplied https://github.com/cbmi/cilantro/issues/72 (see [Install & Setup](https://github.com/cbmi/cilantro/wiki/Install-&-Setup))
  - This is not too different from the current behavior, but ensures it will work immediately out of the box
- [x] Clearly defined and well-documented view classes used to populate the client
  - This enables integrating the default Cilantro layout/UI/behavior into an existing web page
- [x] A utility function(s) for getting URLs relative to Cilantro's navigation via push- and popState (see #89)
  - This ensures existing sites/apps can integrate well from other navigation areas
- [x] Serrano must have an endpoint (it does) that returns all other immediately necessary endpoints to populate the client/session
- [x] Serrano must support CORS (see https://github.com/cbmi/serrano/issues/28)
